version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=colin
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=split
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U colin -d split']
      interval: 5s
      timeout: 5s
      retries: 5

  db-test:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=colin
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=split_test
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U colin -d split_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
